// AUTO-GENERATED by ViPERDSP/tools/viper_layout_gen.py
// DO NOT EDIT BY HAND. Regenerate by running `make layout` after
// any change to ViPERDSP/include/ViPERParams.h.
//
// Mirrors viper::ViPERParams byte layout for the shm producer in
// ConfigChannel.kt. Field offsets are derived from the same C++
// header the AIDL HAL consumer compiles against — Kotlin and C++
// cannot disagree on struct shape.
// ignore_for_file: constant_identifier_names

abstract final class ViperParamsLayout {
  // Root struct: viper::ViPERParams
  static const int SIZE = 1144;
  static const int masterLimiter = 0;
  static const int playbackGainControl = 12;
  static const int lufs = 28;
  static const int fetCompressor = 44;
  static const int bass = 112;
  static const int bassMono = 132;
  static const int psychoacousticBass = 152;
  static const int spectrumExtension = 172;
  static const int equalizer = 184;
  static const int convolver = 316;
  static const int ddc = 324;
  static const int fieldSurround = 328;
  static const int diffSurround = 344;
  static const int stereoImager = 364;
  static const int headphoneSurround = 388;
  static const int reverb = 396;
  static const int dynamicSystem = 420;
  static const int clarity = 452;
  static const int cure = 464;
  static const int tubeSimulator = 472;
  static const int analogX = 476;
  static const int speakerCorrection = 484;
  static const int multibandCompressor = 488;
  static const int dynamicEq = 856;
}

abstract final class MasterLimiterLayout {
  static const int SIZE = 12;
  static const int threshold = 0;
  static const int outputVolume = 4;
  static const int channelPan = 8;
}

abstract final class PlaybackGainControlLayout {
  static const int SIZE = 16;
  static const int enable = 0;
  static const int strength = 4;
  static const int maxGain = 8;
  static const int outputThreshold = 12;
}

abstract final class LufsLayout {
  static const int SIZE = 16;
  static const int enable = 0;
  static const int target = 4;
  static const int maxGain = 8;
  static const int speed = 12;
}

abstract final class FetCompressorLayout {
  static const int SIZE = 68;
  static const int enable = 0;
  static const int threshold = 4;
  static const int ratio = 8;
  static const int knee = 12;
  static const int kneeAuto = 16;
  static const int gain = 20;
  static const int gainAuto = 24;
  static const int attack = 28;
  static const int attackAuto = 32;
  static const int release = 36;
  static const int releaseAuto = 40;
  static const int kneeMulti = 44;
  static const int maxAttack = 48;
  static const int maxRelease = 52;
  static const int crest = 56;
  static const int adapt = 60;
  static const int noClip = 64;
}

abstract final class BassLayout {
  static const int SIZE = 20;
  static const int enable = 0;
  static const int mode = 4;
  static const int frequency = 8;
  static const int gain = 12;
  static const int antiPop = 16;
}

abstract final class BassMonoLayout {
  static const int SIZE = 20;
  static const int enable = 0;
  static const int mode = 4;
  static const int frequency = 8;
  static const int gain = 12;
  static const int antiPop = 16;
}

abstract final class PsychoacousticBassLayout {
  static const int SIZE = 20;
  static const int enable = 0;
  static const int cutoff = 4;
  static const int intensity = 8;
  static const int harmonicOrder = 12;
  static const int originalLevel = 16;
}

abstract final class SpectrumExtensionLayout {
  static const int SIZE = 12;
  static const int enable = 0;
  static const int strength = 4;
  static const int exciter = 8;
}

abstract final class EqualizerLayout {
  static const int SIZE = 132;
  static const int enable = 0;
  static const int bandCount = 4;
  static const int bandLevels = 8;
  static const int bandLevelsLen = 31;
}

abstract final class ConvolverLayout {
  static const int SIZE = 8;
  static const int enable = 0;
  static const int crossChannel = 4;
}

abstract final class DdcLayout {
  static const int SIZE = 1;
  static const int enable = 0;
}

abstract final class FieldSurroundLayout {
  static const int SIZE = 16;
  static const int enable = 0;
  static const int widening = 4;
  static const int midImage = 8;
  static const int depth = 12;
}

abstract final class DiffSurroundLayout {
  static const int SIZE = 20;
  static const int enable = 0;
  static const int delay = 4;
  static const int reverse = 8;
  static const int wetDryMix = 12;
  static const int lpCutoff = 16;
}

abstract final class StereoImagerLayout {
  static const int SIZE = 24;
  static const int enable = 0;
  static const int lowWidth = 4;
  static const int midWidth = 8;
  static const int highWidth = 12;
  static const int lowCrossover = 16;
  static const int highCrossover = 20;
}

abstract final class HeadphoneSurroundLayout {
  static const int SIZE = 8;
  static const int enable = 0;
  static const int quality = 4;
}

abstract final class ReverbLayout {
  static const int SIZE = 24;
  static const int enable = 0;
  static const int roomSize = 4;
  static const int width = 8;
  static const int damp = 12;
  static const int wet = 16;
  static const int dry = 20;
}

abstract final class DynamicSystemLayout {
  static const int SIZE = 32;
  static const int enable = 0;
  static const int xCoeffLow = 4;
  static const int xCoeffHigh = 8;
  static const int yCoeffLow = 12;
  static const int yCoeffHigh = 16;
  static const int sideGainLow = 20;
  static const int sideGainHigh = 24;
  static const int strength = 28;
}

abstract final class ClarityLayout {
  static const int SIZE = 12;
  static const int enable = 0;
  static const int mode = 4;
  static const int gain = 8;
}

abstract final class CureLayout {
  static const int SIZE = 8;
  static const int enable = 0;
  static const int crossfeedPreset = 4;
}

abstract final class TubeSimulatorLayout {
  static const int SIZE = 1;
  static const int enable = 0;
}

abstract final class AnalogXLayout {
  static const int SIZE = 8;
  static const int enable = 0;
  static const int mode = 4;
}

abstract final class SpeakerCorrectionLayout {
  static const int SIZE = 1;
  static const int enable = 0;
}

abstract final class MultibandCompressorBandLayout {
  static const int SIZE = 68;
  static const int enable = 0;
  static const int threshold = 4;
  static const int ratio = 8;
  static const int knee = 12;
  static const int kneeAuto = 16;
  static const int gain = 20;
  static const int gainAuto = 24;
  static const int attack = 28;
  static const int attackAuto = 32;
  static const int release = 36;
  static const int releaseAuto = 40;
  static const int kneeMulti = 44;
  static const int maxAttack = 48;
  static const int maxRelease = 52;
  static const int crest = 56;
  static const int adapt = 60;
  static const int noClip = 64;
}

abstract final class MultibandCompressorLayout {
  static const int SIZE = 368;
  static const int enable = 0;
  static const int bandCount = 4;
  static const int crossoverFrequencies = 8;
  static const int crossoverFrequenciesLen = 5;
  static const int bands = 28;
  static const int bandsLen = 5;
}

abstract final class DynamicEqBandLayout {
  static const int SIZE = 28;
  static const int frequency = 0;
  static const int q = 4;
  static const int gain = 8;
  static const int threshold = 12;
  static const int attack = 16;
  static const int release = 20;
  static const int filterType = 24;
}

abstract final class DynamicEqLayout {
  static const int SIZE = 288;
  static const int enable = 0;
  static const int bandCount = 4;
  static const int bands = 8;
  static const int bandsLen = 10;
}
